service: xact-assessment-api

custom:
  apiVersion: v1


provider:
  name: aws
  runtime: java11
  region: us-east-1
  versionFunctions: false
  stage: dev
  timeout: 30

package:
  artifact: ./build/libs/XAct_Assessment_API-0.1-all.jar

functions:

  inventory-data:
    handler: com.xact.assessment.functions.AssessmentHandler
    events:
      - http:
          path: /${self:custom.apiVersion}/{proxy+}
          method: any
