service: xact-assessment-api

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.project-xact.in
    createRoute53Record: true
  apiVersion: v1

provider:
  name: aws
  runtime: java11
  region: ap-south-1
  versionFunctions: false
  timeout: 30
  memorySize: 1024

package:
  artifact: ./build/libs/XAct_Assessment_API-0.1-all.jar

functions:

  assessment-function:
    handler: com.xact.assessment.functions.AssessmentHandler
    events:
      - http:
          path: /${self:custom.apiVersion}/{proxy+}
          method: any
      - http:
          path: /health
          method: GET
