micronaut:
  http:
    client:
      read-timeout: 1m
  application:
    name: XAct_Assessment_API
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - https://dev.xact.thoughtworks.net
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}'
        signatures:
          jwks:
            okta:
              url: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}/v1/keys'

datasources:
  default:
    url: jdbc:postgresql://xact-db-np.cs3hcgchak2w.ap-south-1.rds.amazonaws.com:5432/xactdev?sslmode=require
    //url: jdbc:postgresql://xact-db.cs3hcgchak2w.ap-south-1.rds.amazonaws.com:5432/xactdev?sslmode=disable
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PWD}

profile:
  type: "dev"

token:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}
  url: "https://thoughtworks.okta.com"
  endpoint: "/oauth2/aus1fjygi70z7ZtVB0h8/v1/token"
  grantType: "client_credentials"

account:
  url: "https://api.thoughtworks.net/account"
  scope: "account.read.internal"
  endpoint: "/api/accounts"

email:
  url: "https://api.thoughtworks.net"
  scope: "email.send"
  endpoint: "/notification/messages"
  delay: "1m"
  notificationEnabled : true
  maskEmail : false

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

validation:
  email: '^([_A-Za-z0-9-+]+\.?[_A-Za-z0-9-+]+@(thoughtworks.com))$'
