micronaut:
  application:
    name: XAct_Assessment_API
  server:
    port: 8000
    cors:
      enabled: true
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}'
        signatures:
          jwks:
            okta:
              url: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}/v1/keys'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**

#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres?sslmode=disable
#    driverClassName: org.postgresql.Driver
#    username: ${USER}
#    password: ''
#    dialect: POSTGRES


flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

jpa:
  default:
    entity-scan:
      packages: 'com.xact.assessment.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false

validation:
  email: '^([_A-Za-z0-9-+]+\.?[_A-Za-z0-9-+]+@(thoughtworks.com))$'