micronaut:
  http:
    client:
      read-timeout: 1m
  application:
    name: XAct_Assessment_API
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - https://qa.xact.thoughtworks.net
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}'
        signatures:
          jwks:
            okta:
              url: '${OIDC_ISSUER:`https://dev-47045452.okta.com/oauth2/default`}/v1/keys'

profile:
  type: "qa"
  url: "https://qa.xact.thoughtworks.net/assessment/"
  homePageUrl: "https://qa.xact.thoughtworks.net/"
  supportUrl: "https://sites.google.com/thoughtworks.com/x-act"
  microSiteUrl: "https://sites.google.com/thoughtworks.com/x-act"
  feedbackUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdazGMcKL5cURmLZ54JgwBOHk6P7KEpbH0ZcQvaOV78_o2GJA/viewform"

token:
  username: ${AUTH_USERNAME}
  password: ${AUTH_PASSWORD}
  url: "https://thoughtworks.okta.com"
  endpoint: "/oauth2/aus1fjygi70z7ZtVB0h8/v1/token"
  grantType: "client_credentials"

account:
  url: "https://api.thoughtworks.net/account"
  scope: "account.read.internal"
  endpoint: "/api/accounts"
  delay: "4h"
  initialDelay: "1m"

email:
  url: "https://api.thoughtworks.net"
  scope: "email.send"
  endpoint: "/notification/messages"
  delay: "30s"
  notificationEnabled : true
  maskEmail : true
  defaultEmail: "shashank.mishra@thoughtworks.com,jathin.meduri@thoughtworks.com"
  fromEmail: "project-xact@thoughtworks.net"
  name: "X-ACT Support"

notification:
  feedback:
    initialDelay: "1m"
    delay : "1d"
    durationInDays: 29

userQuestion:
  fixedDelay : "1d"

cleanup:
  initialDelay: "1m"
  notification:
    fixedDelay: "60d"
  activityLog:
    fixedDelay: "1d"
  rejectedQuestion:
    fixedDelay: "10d"

identityProvider:
  iss: https://thoughtworks.okta.com/oauth2/default
  userInfo: /v1/userinfo

datasources:
  default:
    url: jdbc:postgresql://xact-db-np.xact.thoughtworks.net:5432/xactqa?sslmode=require
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PWD}

flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true

validation:
  email: '^([_A-Za-z0-9-+]+\.?[_A-Za-z0-9-+]+@(thoughtworks.com))$'
