INSERT INTO tbm_assessment_module(module_id, module_name, category)
VALUES (20, 'Agile Project Management', 1);
INSERT INTO tbm_assessment_module(module_id, module_name, category)
VALUES (21, 'Optimised Evolvability', 6);
------------------------------------------------------------------------
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(57,'Team onboarding',20);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(58,'Project planning',20);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(59,'Team management',20);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(60,'Risk management',20);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(61,'Reporting and Governance',20);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(62,'Infrastructure',21);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(63,'Process',21);
INSERT INTO tbm_assessment_topic(topic_id, topic_name, module) VALUES(64,'Tools & Technologies',21);

INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(143,'Onboarding',57);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(144,'Knowledge management',57);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(145,'Offboarding',57);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(146,'Vision and Work allocation',58);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(147,'Capacity planning',58);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(148,'Velocity predictability',58);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(149,'Release planning',58);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(150,'Ways of working',59);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(151,'Knowledge sharing',59);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(152,'Learning',59);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(153,'Team NPS',59);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(154,'Business contuinity planning',60);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(155,'Dependency/risk management',60);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(156,'Success metrics and reporting',61);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(157,'Communication and governance plan',61);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(158,'Hosting',62);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(159,'Maintenance',62);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(160,'Virtualisation',62);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(161,'Operations',63);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(162,'Delivery',64);
INSERT INTO tbm_assessment_parameter(parameter_id, parameter_name, topic) VALUES(163,'Provisioning',64);

INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(353,'Is there an onboarding plan created for the team(s) that includes functional, technical, team related knowledge?',143);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(354,'Is this plan documented centrally, and is being maintained regularly?',143);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(355,'How are accesses granted to the new team members? Is there a uniform mechanism for this? Who validates that the requied accesses are granted to the team members?',143);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(356,'What mechanism is in place to assess the onboarding of new members, and how are decisions taken on onboarding?',143);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(357,'Who is responsible for onboarding of new team members? Are there any programs like ''buddy programs'' active?',143);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(358,'Are the onboarding and offboarding-related knowledge maintained and updated centrally?',144);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(359,'Who is responsible for updating the onboarding/offboarding content?',144);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(360,'How is feedback gathered from new team members on the onboarding content, and how is the feedback implemented?',144);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(361,'What are the offboarding formalities that have to be cleared before a team member is relieved from the team?',145);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(362,'Is there an offboarding checklist managed? ',145);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(363,'How is it ensured that access to the systems is revoked? What is the mechanism to validate that the accesses are revoked?',145);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(364,'Is a high-level vision for the product team/team(s) defined clearly and articulated to the teams?',146);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(365,'How are the teams and teams'' work aligned to the high-level vision?',146);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(366,'How are teams involved in the prioritisation of the work items for the team? ',146);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(367,'How are the priorities broken down into individual work items, and allocated to the teams?',146);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(368,'What are the planning cycles, how is work being allocated, and commitments being made?',146);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(369,'How do the teams forecast their capacity available for the planning cycles?',147);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(370,'How is capacity being considered for unplanned work and defects?',147);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(371,'What various parameters are considered in calculating the available capacity for the upcoming sprints and planning cycles?',147);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(372,'What velocity variance is seen across the last few (4) sprints for the teams? What are the reasons for this variance?',148);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(373,'Are the teams able to reliably predict the velocity for the upcoming sprint? If not, what are the potential reasons?',148);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(374,'What is the nature of planned vs. unplanned work for the teams?',148);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(375,'Are the teams able to release within the planned scheduled windows?',149);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(376,'How are NFRs and NFR testing being incorporated into the release cycles?',149);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(377,'What is the process of overall regression testing? How fast are the changes able to be incorporated into the trunk build?',149);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(378,'What is the post-production testing process in place? How quickly are production defects addressed?',149);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(379,'Is there a good rollback mechanism setup in place?',149);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(380,'Are the roles and responsibilities defined for the team members?',150);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(381,'Are ways of working defined and/or understood by all the team members?',150);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(382,'Are there any knowledge silos created within the team? How are contingencies being created?',150);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(383,'What kind of conflicts is arising in the team? How are they being handled?',150);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(384,'Does the team take collective accountability for the outcomes?',150);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(385,'How is knowledge shared across the various team members?',151);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(386,'Is there a defined knowledge management process/tool that is being used, and maintained?',151);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(387,'How do individual team members get an opportunity to learn? How are the teams ensuring that the team members get stretch opportunities?',152);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(388,'What mechanisms is the team using to share the learnings with other team members?',152);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(389,'How are product deliveries and individual aspirations balanced in the team?',152);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(390,'Does the team feel productive as a whole? What gaps are identified, if any?',153);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(391,'Is there a way to check the health of the team at regular intervals?',153);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(392,'What are the NPS scores (or likes) for the last 3 cycles? What are the major gaps?',153);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(393,'Is there an active business continuity plan in place?',154);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(394,'Has the BCP been tested, and how long does it take to be put in action?',154);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(395,'How are risks being actively identified, managed and mitigated?',155);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(396,'How are dependencies being tracked, and managed? ',155);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(397,'Are success measures for the team defined and well understood across the team?',156);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(398,'What mechanism is there to track the key metrics? How often are these metrics collected?',156);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(399,'How are key metrics taken into consideration for decision-making?',156);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(400,'What kind of reports are generated for the articulation of the success/failure of the team''s work?',156);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(401,'How is a team''s success related to the (business) outcomes?',156);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(402,'Is there an established communication plan for both intra and inter team purposes?',157);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(403,'How are risks articulated to the key decision makers/sponsors? ',157);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(404,'What governance mechanism is implemented for tracking the success of the program/project?',157);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(405,'Are you using an orchestrator currently? ',158);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(406,'How many microservices exist currently?',158);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(407,'What areas are covered by self-healing? What is its efficiency? ',159);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(408,'Is maintenance driven by AI/ML? If yes, what % of operations get covered through this?',159);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(409,'Is the application containerized? Which tool is being used',160);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(410,'What % of your actions/efforts/decision-making is data-driven? Can you share some examples',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(411,'What % of your actions/efforts/decision-making is AI-driven',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(412,'Does the microservice have a single point of failure? What is the remediation in place for it?',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(413,'Does it have more than one point of failure? What is the remediation in place for it?',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(414,'Have all of the microservice’s failure scenarios and possible catastrophes been identified? If yes, can you share data on them? ',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(415,'Are there clearly defined levels of failure? If yes, what is the categorisation?',161);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(416,'Do you perform continuous deployment? Are there quality gates for continuous deployment',162);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(417,'Do you perform continuous delivery?',162);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(418,'What is the freq of deployment over the last 1 year',162);
INSERT INTO tbm_assessment_question(question_id, question_text, parameter) VALUES(419,'Are you serverless? If yes, how many services are currently serverless or are soon going to be serverless?',163);

INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (62,'ONE','Single monolith application deployed as is on a server. No containerization or orchestration is involved. Many manual steps are involved in the overall deployment process. The maintenance process is reactive and production issue-based. No self-healing mechanisms in place');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (62,'TWO','The application is split into microservices. However, separation is not absolute, there are many inter-dependencies which lead to complicated deployment processes. Containerization is followed, however, no orchestration as such is in place. Maintenance is more reactive along with a few proactive measures like some amount of monitoring and alerting setup. ');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (62,'THREE','Microservices-based deployments. Canary deployments are possible owing to the proper separation of responsibilities between the microservices'' components. Containerized and orchestrated deployment in place. Sel-healing mechanisms were thought of, but, not implemented. AI/ML is not in use for maintenance aspects or used at a very rudimentary level. ');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (62,'FOUR','Microservices, following canary deployments. Very well containerized and orchestrated. Maintenance is more proactive with proper monitoring and alerting mechanisms put in place. Self-healing mechanisms are in vogue and constantly tracked. AI/ML mechanisms are put in place and followed for various metrics analysis and potential improvements. ');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (62,'FIVE','All in 4 + AI/ML is very widely used across the board for trend analysis and improvement suggestions. Self-healing mechanisms are in place and very effectively implemented and tracked.');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (63,'ONE','Not a microservices environment. Even if so, the separation of the responsibilities across the services is not clear. Multiple points of failure. Sometimes, not all points of potential failure have been identified and tracked. Levels of failures are not categorised and tracked. No data is available for the past 6 months or so. Not AI is driven in maintenance and decision making');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (63,'TWO','Microservices environment. Points of failure for the environment are identified but not well-tracked. Data are available only for the last 3 months. No structured remediation policies are in place for the points of failure. AI-driven decision-making is not in vogue');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (63,'THREE','Points of failure are identified and tracked. Remediation strategies are in place and well defined. Sel-healing mechanisms are in place too for remediation and all are tracked effectively. Data on the failures are tracked and available for the last 6 months. AI is not in vogue');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (63,'FOUR','All points of failure are properly identified and remediation strategies are in place and very effective. Self-healing mechanisms are established and effectively put in place. Data on the failures are tracked and available for a year or more. Levels of failure are categorised and tracked. Many decisions on the maintenance and other fronts are AI-driven albeit being in their rudimentary stages');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (63,'FIVE','All in 4 + AI is widely implemented and most decisions are influenced by AI data. Points of failure are identified and categorised and remediation strategies are in place and well established.');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (64,'ONE','CI/CD is in place but not very much a norm or followed. Most of the deployments are Adhoc and involve manual steps. Freq of deployment is not structured or tracked, again Adhoc and mostly driven by need. No quality gates for deployments. Serverless is not in use');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (64,'TWO','CI/CD is in place and followed to some extent. Again, the deployment frequency is not structured or defined. And, deployments could still involve some manual steps. No quality gates for deployment, even if present, is very rudimentary and not adhered to. Serverless is not implemented. Data over the freq of deployment is not tracked very effectively.');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (64,'THREE','CI/CD is in vogue. Well established and followed. Deployment freq is well established but not strictly adhered to. The same goes with Quality gates for deployment. Serverless is not implemented. Data over the freq of deployment is tracked but only available for the past 6 months or so');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (64,'FOUR','CI/CD is well established and is the only way deployments happen. Quality gates are in place and well adhered to. Freq of deployment is very well structured and followed to the dot. Data over the freq of deployment for the past year or more is tracked and available. Serverless is in use on a small scale.');
INSERT INTO tbm_assessment_topic_reference(topic, rating, reference) VALUES (64,'FIVE','All in 4 + completely serverless implementation or going to be, looking ahead in the roadmap within a short duration of time. Data over the freq of deployment for the past year or more is tracked, available and used for trend analysis and optimisations.');

INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (143,'ONE','There is no structured or semi-structured onboarding. New team members depend heavily on the current team members, and every new member has a different onboarding experience.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (143,'TWO','There is some documented onboarding, but majority of the onboarding happens through team memory. Every new member has a different onboarding experience.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (143,'THREE','The onboarding process is semi-structured. The onboarding checklist mostly exists, but with gaps. Updates to onboarding content/process are infrequent, and not the latest. ');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (143,'FOUR','The onboarding process is structured. New team members know who to reach out to for various concerns. All members go through a similar onboarding process, and there is consistency in the process. There are limited gaps in onboarding efficiency.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (143,'FIVE','The onboarding process is well documented and maintained. Most of the process works in a self serv manner.
The onboarding process is very efficient, and all new members go through a very similar experience.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (144,'ONE','There are no functional/technical documents available.
There is no knowledge management tools or process put in place.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (144,'TWO','Minimal functional and technical documentation is available. The documentation is fragmented, and new members have to access multiple systems to understand the current state.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (144,'THREE','There is an active knowledge management process/tool in place. Most of the knowledge is up to date, with some gaps.
No process is defined to keep the knowledge management up to date.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (144,'FOUR','There is an active knowledge management process/tool in place. Most of the knowledge is up to date, with very minimal gaps. The process is defined to keep the knowledge management tool up to date. ');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (144,'FIVE','All knowledge is very actively managed and maintained. The team takes collective responsibility to keep the knowledge up to date. The team views knowledge management as one of their key responsibilities.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (145,'ONE','There is no offboarding process or formalities listed.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (145,'TWO','Offboarding happens in an unstructured manner, there are no checks to ensure that the key accesses are revoked when the team members leave.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (145,'THREE','There is an offboarding checklist being maintained. However, compliance is not mandated or governed.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (145,'FOUR','Offboarding checklist is present and up to date. Every team member leaving diligently goes through the offboarding process, and there is a timely audit of access to the system.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (145,'FIVE','Offboarding process is present, with automation put in place for most part. There is timely audit conducted and reported.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (146,'ONE','The vision of the program is not clear and isn''t articulated to the team. The team picks up a variety of work, and at random. Team accountability is not defined clearly.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (146,'TWO','There is high level vision defined, but the teams pick up most work that is adjacent and unrelated to the team charter.  The teams priorities often change, and at random, with individual work items not tied to higher level goal.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (146,'THREE','The team charter is defined, and the team picks up work related to the team objectives. However priorities do change at random and often, and the team picks up work that is unrelated to their area of expertise.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (146,'FOUR','The team charter/objective is clearly defined and articulated to the teams. The team is constantly building expertise in this area, and the work is aligned with the overall objectives.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (146,'FIVE','The team is seen as an exemplary product-centric team, with the team fully in control of the work backlog, priorities, and success metrics. The team proactively looks to innovate and solve problems in the related functional/technical area.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (147,'ONE','There is no capacity planning process in place. Work is allocated and picked up at random.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (147,'TWO','The team has some understanding of the capacity, but it is often incorrect.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (147,'THREE','The team does capacity planning, but often all the parameters are not considered. The team is able to forecast their capacity only 50% of the time.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (147,'FOUR','There is a proper mechanism set in place for capacity planning.  The team is in full control of knowing their upcoming capacity availability and planning for work accordingly.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (147,'FIVE','There is a proper mechanism set in place for capacity planning, and the team is able to predict their capacity for the upcoming planning cycles.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (148,'ONE','Velocity calculations are incorrect or not present. The team isn''t able to predict the velocity for the next cycles.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (148,'TWO','The team''s predictions are mostly incorrect, and off by a large margin. There is a huge variance between planned and actual velocity, and often.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (148,'THREE','The teams are able to predict their velocity within the 75 percentile for 90% of their sprints.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (148,'FOUR','The teams are able to predict their velocities within the 90 percentile for 90% of the sprints.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (148,'FIVE','There is very minimal variance, and the team is able to predict and foresee anamolies based on capacity, nature of work, complexity etc.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (149,'ONE','There is no release planning in place. Every release is handled differently, and hence releases are infrequent.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (149,'TWO','Release checklists are present in fragments, however, releases are time-consuming. They are prone to error and sometimes rolled back.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (149,'THREE','Release happens with a 50% success rate. Releases are streamlined, and the release process is well defined. Some defects escape production, and hotfixes are common.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (149,'FOUR','The release process is streamlined, with most of the steps automated. Releases are frequent and less prone to error. Most defects are avoided pre-deployment through automated gates.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (149,'FIVE','The steps to release are fully/mostly automated, including the rollback mechanism. Defects seldom escape to production, and all CFRs are tested thoroughly and in an automated fashion.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (150,'ONE','Ways of working are not defined, and the teams aren''t aware of knowledge silos.
The team members actively avoid conflict. There is no collaboration between team members.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (150,'TWO','Team members collaborate in their pockets. Knowledge silos exist, and the teams are aware of it. There is no active mitigation to remove the silos.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (150,'THREE','Ways of working are defined and established. There are knowledge silos and hence dependencies within the team. There is a plan to reduce/remove the knowledge silos.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (150,'FOUR','Ways of working are clearly defined, established and followed within the teams.
There are no knowledge silos, and proper contingency is built into the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (150,'FIVE','Ways of working are clearly defined, established and followed within the teams.
There are no knowledge silos. There is a strong sense of collaboration within the team and healthy conflict.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (151,'ONE','Team members don''t share knowledge with each other.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (151,'TWO','Knowledge sharing is inconsistent and minimal.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (151,'THREE','Knowledge sharing happens on a pull basis. There are no mechanisms/forums for sharing knowledge with the entire team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (151,'FOUR','There is a knowledge management tool/process setup in place. This is used regularly, and most of the knowledge is shared proactively by various team members.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (151,'FIVE','Knowledge sharing is self-driven, and the various team members proactively share their learnings with the rest of the team on a time-to-time basis.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (152,'ONE','Team members don''t actively think about learning opportunities on this team. Any learning is incidental.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (152,'TWO','Team members have learning aspirations but they are not aligned with the nature of the work on the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (152,'THREE','Team members have good learning opportunities in their pockets depending on the nature of the work, but there is no active effort on the team to focus and maximize the learning.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (152,'FOUR','There is a good balance of learning and delivery on the project. Most team members are excited and get opportunities to upgrade their capabilities from time to time.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (152,'FIVE','The team proactively looks to create new opportunities for learning. There is a perfect balance of learning and delivery ownership within the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (153,'ONE','Team members are not happy and they actively seek to leave the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (153,'TWO','Most team members are not happy and don''t feel productive. They constantly seek motivation to work with the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (153,'THREE','The team is somewhat engaged, however, they have identified areas of improvement to collectively improve the health of the team.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (153,'FOUR','The team is very engaged, and feels quite productive. There are a few areas requiring major improvements.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (153,'FIVE','The team is an ideal one, and team members look forward to working in the team. It scores high on NPS quarter over quarter.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (154,'ONE','There is no BCP in place.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (154,'TWO','There is a BCP in place, but not been tested. ');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (154,'THREE','There are gaps in the BCP, and it doesn''t account for all uncertainties');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (154,'FOUR','BCP is robust for most of the activities in the project, only a few infrequently used processes aren''t tested.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (154,'FIVE','BCP is robust and has been tested for all uncertainties.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (155,'ONE','Risks and dependencies are not being tracked. The team faces uncertainties often.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (155,'TWO','Risks and dependencies are tracked but not regularly. Mitigation is often not clear and takes time.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (155,'THREE','Risks and dependencies are tracked and managed at regular intervals.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (155,'FOUR','Risks and dependencies are proactively identified and mitigated. There is clear communication with various stakeholders to stay on top of the risks and dependencies.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (155,'FIVE','Risks and dependencies are proactively identified and mitigated. There is clear communication with various stakeholders to stay on top of the risks and dependencies. Various dependent teams collaborate proactively to remove the key risks and dependencies.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (156,'ONE','Success metrics for the team is not defined.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (156,'TWO','Success metrics are defined but dysfunctional. Team doesn''t actively measure these, and no reporting is done on these measures.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (156,'THREE','Team has a good idea of the success measures, but unable to track all of the metrics. There is a lot of manual steps involved in collecting the right metrics, and hence the metrics are inconsistent and time consuming. There is a tendancy for the metrics to be gamed sometimes.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (156,'FOUR','Success metrics are clearly defined, and the team is fully aligned on it. The key metrics are effective, and gets reflected on a regular basis. The team collectively uses this data to improve their effectiveness.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (156,'FIVE','Success metrics are clearly defined, and collection is automated through a central tool. The team uses this data on a regular basis to make important decisions.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (157,'ONE','There is very minimal communication, and collaboration. There is no governance mechanism in place.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (157,'TWO','Communication happens in pockets, and the key stakeholders don''t have full visibility into the teams progress.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (157,'THREE','There is a well defined communication plan. Governance mechanism is defined, but execution is irregular.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (157,'FOUR','Communication and governance mechanism is well defined, and well executed. Stakeholders are regularly kept upto date on the overall progress.');
INSERT INTO tbm_assessment_param_reference(parameter, rating, reference) VALUES (157,'FIVE','Communication and governance mechanism is well defined, and well executed. There is active two way communication between the teams and the sponsors, which keeps the teams fully aligned.');